### ISSUE TITLE
Typos in Tools and Libraries docs

### ISSUE THREAD

**Issue by lowecg** [scicloj/scicloj.github.io#41]
On this page there are several typos:

https://scicloj.github.io/docs/resources/libs/

<img width="372" alt="image" src="https://user-images.githubusercontent.com/928438/170225543-662619c3-1c80-4479-b65b-05e644138b55.png">

explort -> export 

<img width="312" alt="image" src="https://user-images.githubusercontent.com/928438/170225846-a9670220-85ac-4c80-a608-a2f15b805b33.png">

algegra -> algebra 

<img width="474" alt="image" src="https://user-images.githubusercontent.com/928438/170226070-08afaffd-843e-4a38-81ca-b6fd95893066.png">

abstructions -> abstractions

<img width="496" alt="image" src="https://user-images.githubusercontent.com/928438/170226349-cabe010b-7ee6-4f5c-bd53-a3888c8fed64.png">

macine -> machine

**Comment by daslu** [comment]
Thanks, @lowecg! 
Pushed a fix.

**Comment by lowecg** [comment]
You're very welcome :-)
